apiVersion: external-secrets.io/v1
kind: SecretStore
metadata:
  name: {{ .Values.secretStore.name }}
spec:
  provider:
    azurekv:
      authType: WorkloadIdentity
      vaultUrl: {{ required "secretStore.vaultUrl is required" .Values.secretStore.vaultUrl | quote }}
      serviceAccountRef:
        name: {{ .Values.serviceAccount.name }}