apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.serviceAccount.name }}
  annotations:
    azure.workload.identity/client-id: {{ required "workloadIdentity.clientId is required" .Values.workloadIdentity.clientId | quote }}
    azure.workload.identity/tenant-id: {{ required "workloadIdentity.tenantId is required" .Values.workloadIdentity.tenantId | quote }}