{{- if .Values.azurekv.enabled }}
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: okrs-external-secret
  labels:
    {{- include "okrs-backend.labels" . | nindent 4 }}
spec:
  refreshInterval: "1h"
  secretStoreRef:
    name: azure-store
    kind: ClusterSecretStore
  target:
    name: okrs-backend-credentials
    creationPolicy: Owner
  data:
    - secretKey: POSTGRES_PASSWORD
      remoteRef:
        key: postgres-password
    - secretKey: SPRING_REDIS_HOST
      remoteRef:
        key: redis-host
    - secretKey: REDIS_PORT
      remoteRef:
        key: redis-port
    - secretKey: REDIS_PASSWORD
      remoteRef:
        key: redis-password
{{- else }}
apiVersion: v1
kind: Secret
metadata:
  name: okrs-backend-credentials
  labels:
    {{- include "okrs-backend.labels" . | nindent 4 }}
type: Opaque
data:
  {{- range $key, $val := .Values.appSecret }}
  {{ $key }}: {{ $val | b64enc | quote }}
  {{- end }}
{{- end }}