serviceAccount:
  name: okrs-secrets-reader

workloadIdentity:
  clientId: 1723ba78-ed11-46c7-8cfd-ddcf824b015d
  tenantId: f776e96a-9b62-4361-8ed4-89004810cb3a

secretStore:
  name: azure-key-vault
  vaultUrl: https://kv-okrs-dev-hk-ydycrv67h.vault.azure.net/

externalSecrets:
  okrs-backend:
    targetName: okrs-backend-credentials
    refreshInterval: 1h
    data:
      SPRING_DATASOURCE_URL: spring-datasource-url
      POSTGRES_USER: postgres-user
      POSTGRES_PASSWORD: postgres-password
      SPRING_REDIS_HOST: redis-host
      REDIS_PORT: redis-port
      REDIS_PASSWORD: redis-password
      JWT_ACCESS_TOKEN_SECRET: jwt-access-token-secret
      JWT_REFRESH_TOKEN_SECRET: jwt-refresh-token-secret
      SPRING_EMAIL_USERNAME: spring-email-username
      SPRING_EMAIL_PASSWORD: spring-email-password
      SPRING_EMAIL_FROM: spring-email-username
