apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "okrs-backend.fullname" . }}-config
  labels:
    {{- include "okrs-backend.labels" . | nindent 4 }}
data:
  {{- range $key, $val := .Values.appConfig }}
  {{ $key }}: {{ $val | quote }}
  {{- end }}