{{- if .Values.externalSecret.enabled }}
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: {{ include "okrs-backend.fullname" . }}
  labels:
    {{- include "okrs-backend.labels" . | nindent 4 }}
spec:
  refreshInterval: {{ .Values.externalSecret.refreshInterval | quote }}
  secretStoreRef:
    name: {{ .Values.externalSecret.secretStoreRef.name }}
    kind: {{ .Values.externalSecret.secretStoreRef.kind }}
  target:
    name: {{ .Values.secrets.existingSecret }}
    creationPolicy: Owner
    deletionPolicy: Retain
  data:
    {{- range $secretKey, $remoteKey := .Values.externalSecret.data }}
    - secretKey: {{ $secretKey }}
      remoteRef:
        key: {{ $remoteKey }}
    {{- end }}
{{- end }}