{{- if .Values.metrics.serviceMonitor.enabled -}}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "okrs-backend.fullname" . }}
  labels:
    {{- include "okrs-backend.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "okrs-backend.selectorLabels" . | nindent 6 }}
  endpoints:
    - port: management
      path: {{ .Values.metrics.serviceMonitor.path }}
      interval: {{ .Values.metrics.serviceMonitor.interval }}
      scrapeTimeout: {{ .Values.metrics.serviceMonitor.scrapeTimeout }}
{{- end }}
