image:
  repository: acrokrsdevydycrv67hdqyc.azurecr.io/okrs-app
  tag: db2931a62a6de8d912f385e2583c0c1f540e8255
  pullPolicy: IfNotPresent

ingress:
  enabled: false
  hosts: []

persistence:
  enabled: true
  accessMode: ReadWriteMany
  storageClass: azurefile-csi

secrets:
  existingSecret: okrs-backend-credentials

migration:
  enabled: true
  argocdHook: true

appConfig:
  SPRING_LIQUIBASE_ENABLED: "false"
  FILE_STORAGE_PATH: /app/uploads
  JWT_ACCESS_TOKEN_LIFETIME: "900000"
  JWT_REFRESH_TOKEN_LIFETIME: "604800000"

metrics:
  serviceMonitor:
    enabled: true

env:
  springProfile: dev
