{{- if .Values.postgresql.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.postgresql.service.name }}
  labels:
    app.kubernetes.io/name: local-postgres
    app.kubernetes.io/instance: {{ .Release.Name }}
spec:
  clusterIP: None
  ports:
    - name: postgres
      port: {{ .Values.postgresql.service.port }}
      targetPort: postgres
  selector:
    app.kubernetes.io/name: local-postgres
    app.kubernetes.io/instance: {{ .Release.Name }}
{{- end }}
