## Instances
replicaCount: 2

# Image
image:
  repository: okrs-app
  pullPolicy: IfNotPresent
  tag: "latest"

# Environment variables
env:
  springProfile: "qa"

# Networking
service:
  type: ClusterIP
  port: 8080

# External Routing
ingress:
  enabled: true
  className: "nginx"
  hosts:
    - host: api.okrs-project.com
      paths:
        - path: /
          pathType: Prefix

# Compute Resources
resources:
  requests:
    cpu: "250m"
    memory: "512Mi"
  limits:
    cpu: "500m"
    memory: "1Gi"

# Health Checks
probes:
  startup:
    initialDelaySeconds: 15
    periodSeconds: 5
    failureThreshold: 20
  liveness:
    periodSeconds: 10
    failureThreshold: 3
  readiness:
    periodSeconds: 5
    failureThreshold: 2

persistence:
  enabled: true
  size: 1Gi
  mountPath: /app/uploads
  accessMode: ReadWriteOnce

postgres:
  enabled: false

valkey:
  enabled: false
  auth:
    enabled: true
    usersExistingSecret: "okrs-backend-credentials"
    aclUsers:
      default:
        permissions: "~* &* +@all"
        passwordKey: "REDIS_PASSWORD"


appConfig:
  SPRING_LIQUIBASE_ENABLED: "false"
  SPRING_REDIS_HOST: "okrs-test-valkey"
  FILE_STORAGE_PATH: "/app/uploads"